---
# This file contains common variables used throughout the Ansible playbook.
server_name: 43.207.105.100

proxy_pass: "http://127.0.0.1:8000"

supervisor_user: ubuntu

gunicorn_working_directory: /home/ubuntu/new-django

gunicorn_exec_start: /home/ubuntu/new-django/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock todoApp.wsgi:application --bind 0.0.0.0:8002
# Name of the Django application
app_name: "todoApp"

# Git repository URL for the Django application
app_repo: "https://github.com/saurav-kumar-mce/new-django.git"

# Path on the remote server where the Django application will be cloned
app_path: "/home/ubuntu/new-django"

# Path on the remote server where the Python virtual environment for the Django application will be created
virtualenv_path: "/home/ubuntu/new-django/venv"

# Path on the remote server where the Nginx configuration file will be created
nginx_conf_path: "/etc/nginx/sites-available/django"

# Path on the remote server where the Supervisor configuration file will be created
supervisor_conf_path: "/etc/supervisor/conf.d/supervisor.conf"

# Path on the remote server where the Gunicorn service file will be created
gunicorn_service_path: "/etc/systemd/system/gunicorn.service"
