- name: Ensure Supervisor configuration file exists
  copy:
    content: ""
    dest: "{{ supervisor_conf_path }}"
    force: no
    mode: '0644'
    owner: root
    group: root

- name: Append Supervisor configuration
  lineinfile:
    dest: "{{ supervisor_conf_path }}"
    line: |
      [program:todoApp]
      directory=/new-django/
      command=/new-django/myvenv/bin/gunicorn todoApp.wsgi:application -w 4 -b 127.0.0.1:8000
      user=ubuntu
      autostart=true
      autorestart=true
      redirect_stderr=true
    state: present