--- 
- name: Configure Supervisor
  template:
    src: "{{ app_path }}/devops/supervisor.conf.j2"
    dest: "{{ supervisor_conf_path }}"
    remote_src: yes
    mode: '0644'
  notify:
    - Restart Supervisor