# Deploy Django application playbook
# This playbook installs and configures a Django application on remote webservers
---
- name: Deploy Django application
  hosts: webservers # Define the webservers that the application will be deployed to
  become: true # Become the root user on the webservers to run privileged tasks

# Include the roles needed to deploy the Django application
  roles:
    - python  # Install Python and pip
#    - django  # Clone Django app repository, install dependencies, and run migrations
    - nginx   # configure Nginx as reverse proxy for Django app
    - supervisor # Install and configure Supervisor to manage Gunicorn process
    - handlers
    - gunicorn   # configure Gunicorn to run Django app

  vars_files:
    - vars/common.yml   # Load common variables
#    - vars/secrets.yml  # Load encrypted variables for sensitive data
