name: Deploy Django app to EC2

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
  TF_VAR_ami: ${{ secrets.TF_VAR_AMI }}
  TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
  EC2_INSTANCE_USERNAME: ubuntu
  EC2_INSTANCE_PRIVATE_KEY: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init \
            -backend-config="bucket=django-ec2-bucket" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=ap-northeast-1"

      - name: Plan Terraform
        id: plan
        run: |
          cd terraform
          terraform plan -out=plan.tfplan

      - name: Apply Terraform
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve plan.tfplan
        env:
          TF_CLI_AUTO_APPROVE: 1          

      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY  }}
            HOSTNAME : 3.112.209.2
            USER_NAME : ${{ env.EC2_INSTANCE_USERNAME }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          sudo apt-get update
          sudo apt-get install -y supervisor nginx
          sudo rm /etc/nginx/sites-enabled/default
          sudo systemctl restart nginx
          sudo systemctl reload nginx
          sudo supervisorctl reread
          sudo supervisorctl update
          sudo supervisorctl start django
          cd ~/
          sudo git clone https://github.com/saurav-kumar-mce/ec2-django.git /home/ubuntu/ec2-django
          cd ~/ec2-django
          sudo apt-get install -y python3-pip
          pip install django
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo ln -s /etc/nginx/sites-available/django /etc/nginx/sites-enabled/
          sudo systemctl restart nginx
          '