- name: Deploy Django application
  hosts: webservers
  become: true

  vars:
    app_name: "todoApp"
    app_repo: "https://github.com/saurav-kumar-mce/new-django.git"
    app_path: "/home/ubuntu/new-django"
    virtualenv_path: "/home/ubuntu/new-django/venv"
    nginx_conf_path: "/etc/nginx/sites-available/django"
    supervisor_conf_path: "/etc/supervisor/conf.d/supervisor.conf"
    gunicorn_service_path: "/etc/systemd/system/gunicorn.service"

  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: latest

    - name: Clone repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_path }}"
        clone: yes
        update: yes
        force: yes

    - name: Create virtual environment
      command: python3 -m venv "{{ virtualenv_path }}"
      args:
        creates: "{{ virtualenv_path }}"

#    - name: Install Python packages in virtual environment
#      pip:
#        requirements: "{{ app_path }}/requirements.txt"
#        virtualenv: "{{ virtualenv_path }}"

    - name: Configure Nginx
      template:
        src: "{{ app_path }}/devops/nginx.conf"
        dest: "{{ nginx_conf_path }}"
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload Nginx

    - name: Enable Nginx site
      file:
        src: "{{ nginx_conf_path }}"
        dest: "/etc/nginx/sites-enabled/django"
        state: link

    - name: Configure Supervisor
      template:
        src: "{{ app_path }}/devops/supervisor.conf"
        dest: "{{ supervisor_conf_path }}"
      notify:
        - Restart Gunicorn

    - name: Configure Gunicorn service
      template:
        src: "{{ app_path }}/devops/gunicorn.service"
        dest: "{{ gunicorn_service_path }}"
        owner: root
        group: root
        mode: '0644'

    - name: Start Gunicorn
      systemd:
        name: gunicorn
        state: started
        enabled: yes

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded

    - name: Restart Gunicorn
      systemd:
        name: gunicorn
        state: restarted
