---
- name: Install dependencies
  become: true
  hosts: webservers
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
          - python3.10-venv
        state: latest

    - name: Install required packages
      pip:
        name: "{{ item }}"
      with_items:
        - Django
        - gunicorn
        - psycopg2-binary

- name: Deploy Django application
  become: true
  hosts: webservers
  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/saurav-kumar-mce/https://github.com/saurav-kumar-mce/new-django.git
        dest: "/home/ubuntu/{{ new-django }}"
        clone: yes
        update: yes
        force: yes

    - name: Copy Django application files
      copy:
        src: "{{ playbook_dir }}/{{ new-django }}/"
        dest: "/home/ubuntu/{{ new-django }}/"
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      notify:
        - Restart Gunicorn

    - name: Create virtual environment
      command: python3 -m venv /home/ubuntu/{{ new-django }}/myvenv
      args:
        creates: /home/ubuntu/{{ new-django }}/myvenv

    - name: Install Python packages in virtual environment
      pip:
        requirements: /home/ubuntu/{{ new-django }}/requirements.txt
        virtualenv: /home/ubuntu/{{ new-django }}/myvenv

    - name: Configure Gunicorn
      template:
        src: "{{ playbook_dir }}/gunicorn.service.j2"
        dest: /etc/systemd/system/gunicorn.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload Systemd

    - name: Start Gunicorn
      shell: |
        source /home/ubuntu/{{ new-django }}/myvenv/bin/activate
        cd /home/ubuntu/{{ new-django }}/
        gunicorn todoApp.wsgi:application --bind 0.0.0.0:8000
      environment:
        PATH: "/home/ubuntu/{{ new-django }}/myvenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      notify:
        - Reload Nginx

  handlers:
    - name: Restart Gunicorn
      systemd:
        name: gunicorn
        state: restarted

    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded

    - name: Reload Systemd
      systemd:
        daemon_reload: yes
